services:
  caddy:
    container_name: caddy-p8zb3g
    image: caddy:2.5.2-alpine
    tty: false
    stdin_open: false
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/caddy/web:/srv
      - $PWD/caddy/tls:/tls
      # - $PWD/caddy/data:/data
      # - $PWD/caddy/config:/config
    networks:
      - main
  portainer:
    container_name: portainer-zkz374
    image: portainer/portainer-ce:linux-amd64-2.16.2-alpine
    tty: false
    stdin_open: false
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/portainer/data/:/data
    networks:
      - main
  nodejs:
    container_name: nodejs-duj325
    image: node:18-alpine3.16
    tty: true
    stdin_open: true
    working_dir: /app
    command: node server.js
    restart: unless-stopped
    volumes:
      - $PWD/nodejs:/app
    networks:
      - main

networks:
  main:
    name: net-5sfd3p
    external: false
